name: Merge PR to Main on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  cherry_pick_to_main:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    if: ${{ contains(github.event.pull_request.labels.*.name, 'tested') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

    #   - name: Configure Git
    #     run: |
    #       git config user.name "${{ github.actor }}"
    #       git config user.email "${{ github.actor }}@users.noreply.github.com
      - uses: actions/checkout@v3
      - uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        id: cherry-pick
        with:
          branch: main
          force: true
          labels: tested
      - run: |
            echo "${{ steps.cherry-pick }}"
            echo "${{ steps.cherry-pick.outputs }}" 
            echo "${{ toJSON(steps.cherry-pick.outputs) }}"


      - name: Remote View
        run: |
            git remote -v


      - name: Cherry-Pick PR Commits
        run: |
              # Get the PR number
              PR_NUMBER=$(echo ${{ github.event.pull_request.number }})
              
              # Fetch the PR commits
              git fetch origin pull/$PR_NUMBER/head
    
              git checkout main
              git cherry-pick FETCH_HEAD
              git push origin main