name: Merge PR to Main on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  cherry_pick_to_main:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    if: ${{ contains(github.event.pull_request.labels.*.name, 'tested') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into main
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        id: cherry-pick
        with:
          branch: main
          force: true
  
      - name: Find Pull Request Number
        id: find-pr
        run: |
          PR_NUMBER=$(gh pr list --head ${{ steps.cherry-pick.outputs.branch }} --json number --jq '.[0].number')
          echo "Pull Request Number: $PR_NUMBER"
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV    

      - name: Remote View
        run: |
            git remote -v


