name: Merge PR to Main on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  cherry_pick_to_main:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    if: ${{ contains(github.event.pull_request.labels.*.name, 'tested') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

    #   - name: Cherry pick into main
    #     uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
    #     id: cherry-pick
    #     with:
    #       branch: main
    #       force: true
    

      - name: Remote View
        run: |
            git remote -v


      - name: Cherry-Pick PR Commits
        run: |
              # Get the PR number
              PR_NUMBER=$(echo ${{ github.event.pull_request.number }})
              
              # Fetch the PR commits
              git fetch origin pull/$PR_NUMBER/head
    
              git checkout main
              git cherry-pick FETCH_HEAD
              git push origin main